// ChargeDemoAppDelegate.h
// Stock file generated by XCode
//
#import <UIKit/UIKit.h>

@class ChargeDemoViewController;

@interface ChargeDemoAppDelegate : NSObject <UIApplicationDelegate> {
    UIWindow *window;
    ChargeDemoViewController *viewController;
}

@property (nonatomic, retain) IBOutlet UIWindow *window;
@property (nonatomic, retain) IBOutlet ChargeDemoViewController *viewController;

@end
